version: "2"
services:
  db:
    image: mariadb:10.5.9
    ports:
      - "3206:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "vol_db:/var/lib/mysql"
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  vol_db: {}