apiVersion: apps/v1
kind: Deployment
metadata:
  name: webanalysis
spec:
  selector:
    matchLabels:
      app: webanalysis
  replicas: 1
  template:
    metadata:
      labels:
        app: webanalysis
    spec:
      containers:
        - name: webanalysis
          image: webanalysis-main_app
          imagePullPolicy: Never
          ports:
           - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webanalysis-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: tcp
  selector:
    app: webanalysis
  type: LoadBalancer
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mariadb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mariadb"
  template:
    metadata:
      labels:
        app: "mariadb"
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.5.9
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webanalysis-secrets
                  key: db_root_password
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: maria-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mariadb
  selector:
    app: mariadb
  type: LoadBalancer